### ISSUE TITLE
EXIF: datetime (original) and datetime (digitized) should take precedence over the regular datetime tag

### ISSUE THREAD

**Issue by GoogleCodeExporter** [unix-junkie/synctimestamps#1]
```
Certain software (particularly, Nikon Transfer) updates sets the datetime tag 
to the time when the image was transferred from the camera to the PC.
```

Original issue reported on code.google.com by `andrewb...@gmail.com` on 26 Mar 2013 at 6:40

**Comment by unix-junkie** [comment]
Additionally, some Canon cameras update the _Date and Time_ (`0x0132`) tag if one edits an image using the camera itself. In this case, _Date and Time (original)_ and/or _Date and Time (digitized)_ should also take precedence.
